- name: Create tempdir for zip file
  tempfile:
    state: directory
    path: '{{ ansible_facts.env.HOME }}'
  register: site_zip_temp

- name: Get zip file containing website
  get_url:
    url: '{{ site_zip_url }}'
    dest: '{{ site_zip_temp.path }}'
    force: yes
  register: site_zip_file

- name: Create website directory
  file:
    path: '{{ website_path }}'
    state: directory

- name: Unarchive zip file
  unarchive:
    src: '{{ site_zip_file.dest }}'
    dest: '{{ site_zip_temp.path }}/'
    remote_src: yes

- name: Copy site files to website directory
  copy:
    src: '{{ site_zip_temp.path }}/NaturesSourceWebsite/website_complete/'
    dest: '{{ website_path }}'
    remote_src: yes

- name: Remove tempfile from host
  file:
    path: '{{ site_zip_temp.path }}'
    state: absent

- name: Recursively find document head files
  find:
    paths: '{{ website_path }}'
    recurse: yes
    file_type: file
    patterns:
      - document_head.html
  register: document_heads

- name: Replace incorrect directory in base URL path
  replace:
    path: '{{ item.path }}'
    after: '\s+<base href="'
    before: '/ch\d{2}/nature\d{0,2}/">'
    regexp: '^(.+?)$'
    replace: '{{ base_url }}'
  loop: '{{ document_heads.files }}'
