- name: Submissions | Ensure submissions directories are present
  file:
    path: '{{ submissions_path }}/submission{{ "%02d" | format(item | int) }}'
    state: directory
    recurse: yes
  loop: '{{ range(0, submissions_count + 1) | list }}'

- name: Copy submissions to host
  copy:
    src: submissions/
    dest: '{{ submissions_path }}/'
